--------------------------------------------------------
-- Archivo creado  - miércoles-junio-28-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCION_FARM
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."ACCION_FARM" 
   (	"ID" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPUESTO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."COMPUESTO" 
   (	"ID" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FUNCIONARIO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."FUNCIONARIO" 
   (	"RUT" NUMBER(*,0), 
	"DV" CHAR(1 BYTE), 
	"NOMBRES" VARCHAR2(50 BYTE), 
	"APELLIDO_PAT" VARCHAR2(20 BYTE), 
	"APELLIDO_MAT" VARCHAR2(20 BYTE), 
	"TIPO_FUNC_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LABORATORIO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."LABORATORIO" 
   (	"ID" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICAMENTO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."MEDICAMENTO" 
   (	"CODIGO" VARCHAR2(20 BYTE), 
	"NOM_COMERCIAL" VARCHAR2(50 BYTE), 
	"CONTENIDO" NUMBER(*,0), 
	"UNIDAD_CONT" VARCHAR2(20 BYTE), 
	"U_POR_CAJA" NUMBER(*,0), 
	"STOCK_DISPONIBLE" NUMBER(*,0), 
	"STOCK_FISICO" NUMBER(*,0), 
	"LABORATORIO_ID" NUMBER(*,0), 
	"NOM_GENERICO_ID" NUMBER(*,0), 
	"VIA_ADMINISTRACION_ID" NUMBER(*,0), 
	"PRESENTACION_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICAMENTO_ACCION
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."MEDICAMENTO_ACCION" 
   (	"ACCION_FARM_ID" NUMBER(*,0), 
	"MEDICAMENTO_CODIGO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICAMENTO_COMPUESTO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."MEDICAMENTO_COMPUESTO" 
   (	"COMPUESTO_ID" NUMBER(*,0), 
	"MEDICAMENTO_CODIGO" VARCHAR2(20 BYTE), 
	"CANTIDAD" FLOAT(126), 
	"UNIDAD" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICAMENTO_PARTIDA
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."MEDICAMENTO_PARTIDA" 
   (	"PARTIDA_ID" NUMBER(*,0), 
	"MEDICAMENTO_CODIGO" VARCHAR2(20 BYTE), 
	"CANTIDAD" NUMBER(*,0), 
	"FECHA_VENCIMIENTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOM_GENERICO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."NOM_GENERICO" 
   (	"ID" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PACIENTE
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."PACIENTE" 
   (	"RUT" NUMBER(*,0), 
	"DV" CHAR(1 BYTE), 
	"NOMBRES" VARCHAR2(50 BYTE), 
	"APELLIDO_PAT" VARCHAR2(20 BYTE), 
	"APELLIDO_MAT" VARCHAR2(20 BYTE), 
	"FECHA_NACI" DATE, 
	"SEXO" CHAR(1 BYTE), 
	"ESTADO_CIVIL" VARCHAR2(15 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"FONO" NUMBER(*,0), 
	"FONO2" NUMBER(*,0), 
	"CORREO" VARCHAR2(50 BYTE), 
	"CORREO2" VARCHAR2(50 BYTE), 
	"PREVISION" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTIDA
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."PARTIDA" 
   (	"ID" NUMBER(*,0), 
	"FECHA_ENTREGA" DATE, 
	"PROVEEDOR_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRESENTACION
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."PRESENTACION" 
   (	"ID" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."PROVEEDOR" 
   (	"ID" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECETA
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."RECETA" 
   (	"ID" NUMBER, 
	"FECHA" DATE, 
	"HORA" DATE, 
	"ESTADO" VARCHAR2(20 BYTE), 
	"USUARIO_NOM_USU" VARCHAR2(20 BYTE), 
	"PACIENTE_RUT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECETA_MEDICAMENTO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."RECETA_MEDICAMENTO" 
   (	"MEDICAMENTO_CODIGO" VARCHAR2(20 BYTE), 
	"RECETA_ID" NUMBER, 
	"CANTIDAD" NUMBER(*,0), 
	"UNIDAD_C" VARCHAR2(50 BYTE), 
	"PERIODICIDAD" NUMBER(*,0), 
	"UNIDAD_P" VARCHAR2(50 BYTE), 
	"EXTENSION" NUMBER(*,0), 
	"UNIDAD_E" VARCHAR2(50 BYTE), 
	"CANT_TOTAL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REGISTRO_MERMA
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."REGISTRO_MERMA" 
   (	"ID_REG" NUMBER(*,0), 
	"CANTIDAD" NUMBER(*,0), 
	"MOTIVO" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"FECHA" DATE, 
	"HORA" DATE, 
	"ESTADO" VARCHAR2(50 BYTE), 
	"MEDICAMENTO_CODIGO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPO_FUNC
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."TIPO_FUNC" 
   (	"ID" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."USUARIO" 
   (	"NOM_USU" VARCHAR2(20 BYTE), 
	"CONTRASENA" VARCHAR2(20 BYTE), 
	"FUNCIONARIO_RUT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VIA_ADMINISTRACION
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."VIA_ADMINISTRACION" 
   (	"ID" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence ACCION_FARM_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."ACCION_FARM_SQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMPUESTO_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."COMPUESTO_SQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LABORATORIO_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."LABORATORIO_SQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MERMA_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."MERMA_SQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NOM_GENERICO_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."NOM_GENERICO_SQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PARTIDA_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."PARTIDA_SQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRESENTACION_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."PRESENTACION_SQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PROVEEDOR_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."PROVEEDOR_SQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RECETA_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."RECETA_SQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VIA_ADMI_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."VIA_ADMI_SQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into PORTAFOLIO.ACCION_FARM
SET DEFINE OFF;
REM INSERTING into PORTAFOLIO.COMPUESTO
SET DEFINE OFF;
Insert into PORTAFOLIO.COMPUESTO (ID,DESCRIPCION) values ('1','Alguncompuesto');
REM INSERTING into PORTAFOLIO.FUNCIONARIO
SET DEFINE OFF;
Insert into PORTAFOLIO.FUNCIONARIO (RUT,DV,NOMBRES,APELLIDO_PAT,APELLIDO_MAT,TIPO_FUNC_ID) values ('17657894','5','Hector Felipe','Gonzalez','Fernandez','3');
Insert into PORTAFOLIO.FUNCIONARIO (RUT,DV,NOMBRES,APELLIDO_PAT,APELLIDO_MAT,TIPO_FUNC_ID) values ('12345678','2','Juan Topo','Karambio','Cuesta','1');
Insert into PORTAFOLIO.FUNCIONARIO (RUT,DV,NOMBRES,APELLIDO_PAT,APELLIDO_MAT,TIPO_FUNC_ID) values ('1','1','choro','naco','yquepaa','3');
REM INSERTING into PORTAFOLIO.LABORATORIO
SET DEFINE OFF;
REM INSERTING into PORTAFOLIO.MEDICAMENTO
SET DEFINE OFF;
REM INSERTING into PORTAFOLIO.MEDICAMENTO_ACCION
SET DEFINE OFF;
REM INSERTING into PORTAFOLIO.MEDICAMENTO_COMPUESTO
SET DEFINE OFF;
REM INSERTING into PORTAFOLIO.MEDICAMENTO_PARTIDA
SET DEFINE OFF;
REM INSERTING into PORTAFOLIO.NOM_GENERICO
SET DEFINE OFF;
REM INSERTING into PORTAFOLIO.PACIENTE
SET DEFINE OFF;
Insert into PORTAFOLIO.PACIENTE (RUT,DV,NOMBRES,APELLIDO_PAT,APELLIDO_MAT,FECHA_NACI,SEXO,ESTADO_CIVIL,DIRECCION,FONO,FONO2,CORREO,CORREO2,PREVISION) values ('17753134','0','Sebastián Elías','Cabello','Pastén',to_date('17/01/91','DD/MM/RR'),'M','Soltero/a','Inglaterra 330, Viña del mar','98826247',null,'seba.cabello91@gmail.com',null,'FONASA');
REM INSERTING into PORTAFOLIO.PARTIDA
SET DEFINE OFF;
REM INSERTING into PORTAFOLIO.PRESENTACION
SET DEFINE OFF;
REM INSERTING into PORTAFOLIO.PROVEEDOR
SET DEFINE OFF;
Insert into PORTAFOLIO.PROVEEDOR (ID,DESCRIPCION) values ('1','Algo');
REM INSERTING into PORTAFOLIO.RECETA
SET DEFINE OFF;
REM INSERTING into PORTAFOLIO.RECETA_MEDICAMENTO
SET DEFINE OFF;
REM INSERTING into PORTAFOLIO.REGISTRO_MERMA
SET DEFINE OFF;
REM INSERTING into PORTAFOLIO.TIPO_FUNC
SET DEFINE OFF;
Insert into PORTAFOLIO.TIPO_FUNC (ID,DESCRIPCION) values ('3','Administrador');
Insert into PORTAFOLIO.TIPO_FUNC (ID,DESCRIPCION) values ('1','Médico');
Insert into PORTAFOLIO.TIPO_FUNC (ID,DESCRIPCION) values ('2','Farmacéutico');
REM INSERTING into PORTAFOLIO.USUARIO
SET DEFINE OFF;
Insert into PORTAFOLIO.USUARIO (NOM_USU,CONTRASENA,FUNCIONARIO_RUT) values ('admin1','MQAyADMA','17657894');
Insert into PORTAFOLIO.USUARIO (NOM_USU,CONTRASENA,FUNCIONARIO_RUT) values ('pedro123','123','12345678');
Insert into PORTAFOLIO.USUARIO (NOM_USU,CONTRASENA,FUNCIONARIO_RUT) values ('admin2','YQBkAG0AaQBuAA==','1');
REM INSERTING into PORTAFOLIO.VIA_ADMINISTRACION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ACCION_FARM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."ACCION_FARM_PK" ON "PORTAFOLIO"."ACCION_FARM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMPUESTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."COMPUESTO_PK" ON "PORTAFOLIO"."COMPUESTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FUNCIONARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."FUNCIONARIO_PK" ON "PORTAFOLIO"."FUNCIONARIO" ("RUT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LABORATORIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."LABORATORIO_PK" ON "PORTAFOLIO"."LABORATORIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEDICAMENTO_PARTIDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."MEDICAMENTO_PARTIDA_PK" ON "PORTAFOLIO"."MEDICAMENTO_PARTIDA" ("PARTIDA_ID", "MEDICAMENTO_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEDICAMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."MEDICAMENTO_PK" ON "PORTAFOLIO"."MEDICAMENTO" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NOM_GENERICO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."NOM_GENERICO_PK" ON "PORTAFOLIO"."NOM_GENERICO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PACIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."PACIENTE_PK" ON "PORTAFOLIO"."PACIENTE" ("RUT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARTIDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."PARTIDA_PK" ON "PORTAFOLIO"."PARTIDA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRESENTACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."PRESENTACION_PK" ON "PORTAFOLIO"."PRESENTACION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROVEEDOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."PROVEEDOR_PK" ON "PORTAFOLIO"."PROVEEDOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECETA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."RECETA_PK" ON "PORTAFOLIO"."RECETA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REGISTRO_MERMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."REGISTRO_MERMA_PK" ON "PORTAFOLIO"."REGISTRO_MERMA" ("ID_REG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RELATION_13_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."RELATION_13_PK" ON "PORTAFOLIO"."MEDICAMENTO_ACCION" ("ACCION_FARM_ID", "MEDICAMENTO_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RELATION_7_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."RELATION_7_PK" ON "PORTAFOLIO"."RECETA_MEDICAMENTO" ("MEDICAMENTO_CODIGO", "RECETA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RELATION_8_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."RELATION_8_PK" ON "PORTAFOLIO"."MEDICAMENTO_COMPUESTO" ("COMPUESTO_ID", "MEDICAMENTO_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_FUNC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."TIPO_FUNC_PK" ON "PORTAFOLIO"."TIPO_FUNC" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USUARIO__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."USUARIO__IDX" ON "PORTAFOLIO"."USUARIO" ("FUNCIONARIO_RUT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."USUARIO_PK" ON "PORTAFOLIO"."USUARIO" ("NOM_USU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VIA_ADMINISTRACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."VIA_ADMINISTRACION_PK" ON "PORTAFOLIO"."VIA_ADMINISTRACION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_INGRESAR_ACCION_FARM
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."TRG_INGRESAR_ACCION_FARM" 
BEFORE INSERT ON ACCION_FARM
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT ACCION_FARM_SQ.NEXTVAL INTO valorSecuencia FROM DUAL;
:NEW.ID := valorSecuencia;
END;
/
ALTER TRIGGER "PORTAFOLIO"."TRG_INGRESAR_ACCION_FARM" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_INGRESAR_COMPUESTO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."TRG_INGRESAR_COMPUESTO" 
BEFORE INSERT ON COMPUESTO
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT COMPUESTO_SQ.NEXTVAL INTO valorSecuencia FROM DUAL;
:NEW.ID := valorSecuencia;
END;
/
ALTER TRIGGER "PORTAFOLIO"."TRG_INGRESAR_COMPUESTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_INGRESAR_LABORATORIO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."TRG_INGRESAR_LABORATORIO" 
BEFORE INSERT ON LABORATORIO
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT LABORATORIO_SQ.NEXTVAL INTO valorSecuencia FROM DUAL;
:NEW.ID := valorSecuencia;
END;
/
ALTER TRIGGER "PORTAFOLIO"."TRG_INGRESAR_LABORATORIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_INGRESAR_MERMA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."TRG_INGRESAR_MERMA" 
BEFORE INSERT ON REGISTRO_MERMA
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT MERMA_SQ.NEXTVAL INTO valorSecuencia FROM DUAL;
:NEW.ID_REG := valorSecuencia;
END;
/
ALTER TRIGGER "PORTAFOLIO"."TRG_INGRESAR_MERMA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_NOM_GENERICO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."TRG_NOM_GENERICO" 
BEFORE INSERT ON NOM_GENERICO
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT NOM_GENERICO_SQ.NEXTVAL INTO valorSecuencia FROM DUAL;
:NEW.ID := valorSecuencia;
END;
/
ALTER TRIGGER "PORTAFOLIO"."TRG_NOM_GENERICO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PRESENTACION
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."TRG_PRESENTACION" 
BEFORE INSERT ON PRESENTACION
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT PRESENTACION_SQ.NEXTVAL INTO valorSecuencia FROM DUAL;
:NEW.ID := valorSecuencia;
END;
/
ALTER TRIGGER "PORTAFOLIO"."TRG_PRESENTACION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PROVEEDOR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."TRG_PROVEEDOR" 
BEFORE INSERT ON PROVEEDOR
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT PROVEEDOR_SQ.NEXTVAL INTO valorSecuencia FROM DUAL;
:NEW.ID := valorSecuencia;
END;
/
ALTER TRIGGER "PORTAFOLIO"."TRG_PROVEEDOR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RECETA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."TRG_RECETA" 
BEFORE INSERT ON RECETA
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT RECETA_SQ.NEXTVAL INTO valorSecuencia FROM DUAL;
:NEW.ID := valorSecuencia;
END;
/
ALTER TRIGGER "PORTAFOLIO"."TRG_RECETA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_VIA_ADMI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."TRG_VIA_ADMI" 
BEFORE INSERT ON VIA_ADMINISTRACION
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT VIA_ADMI_SQ.NEXTVAL INTO valorSecuencia FROM DUAL;
:NEW.ID := valorSecuencia;
END;
/
ALTER TRIGGER "PORTAFOLIO"."TRG_VIA_ADMI" ENABLE;
--------------------------------------------------------
--  Constraints for Table ACCION_FARM
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."ACCION_FARM" ADD CONSTRAINT "ACCION_FARM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."ACCION_FARM" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."ACCION_FARM" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPUESTO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."COMPUESTO" ADD CONSTRAINT "COMPUESTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."COMPUESTO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."COMPUESTO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FUNCIONARIO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."FUNCIONARIO" ADD CONSTRAINT "FUNCIONARIO_PK" PRIMARY KEY ("RUT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."FUNCIONARIO" MODIFY ("TIPO_FUNC_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."FUNCIONARIO" MODIFY ("APELLIDO_MAT" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."FUNCIONARIO" MODIFY ("APELLIDO_PAT" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."FUNCIONARIO" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."FUNCIONARIO" MODIFY ("DV" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."FUNCIONARIO" MODIFY ("RUT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LABORATORIO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."LABORATORIO" ADD CONSTRAINT "LABORATORIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."LABORATORIO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."LABORATORIO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICAMENTO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO" ADD CONSTRAINT "MEDICAMENTO_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO" MODIFY ("PRESENTACION_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO" MODIFY ("VIA_ADMINISTRACION_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO" MODIFY ("NOM_GENERICO_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO" MODIFY ("LABORATORIO_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO" MODIFY ("STOCK_FISICO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO" MODIFY ("STOCK_DISPONIBLE" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO" MODIFY ("U_POR_CAJA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO" MODIFY ("UNIDAD_CONT" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO" MODIFY ("CONTENIDO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO" MODIFY ("NOM_COMERCIAL" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICAMENTO_ACCION
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_ACCION" ADD CONSTRAINT "RELATION_13_PK" PRIMARY KEY ("ACCION_FARM_ID", "MEDICAMENTO_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_ACCION" MODIFY ("MEDICAMENTO_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_ACCION" MODIFY ("ACCION_FARM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICAMENTO_COMPUESTO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_COMPUESTO" ADD CONSTRAINT "RELATION_8_PK" PRIMARY KEY ("COMPUESTO_ID", "MEDICAMENTO_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_COMPUESTO" MODIFY ("UNIDAD" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_COMPUESTO" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_COMPUESTO" MODIFY ("MEDICAMENTO_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_COMPUESTO" MODIFY ("COMPUESTO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICAMENTO_PARTIDA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_PARTIDA" ADD CONSTRAINT "MEDICAMENTO_PARTIDA_PK" PRIMARY KEY ("PARTIDA_ID", "MEDICAMENTO_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_PARTIDA" MODIFY ("FECHA_VENCIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_PARTIDA" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_PARTIDA" MODIFY ("MEDICAMENTO_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_PARTIDA" MODIFY ("PARTIDA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOM_GENERICO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."NOM_GENERICO" ADD CONSTRAINT "NOM_GENERICO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."NOM_GENERICO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."NOM_GENERICO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PACIENTE
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."PACIENTE" ADD CONSTRAINT "PACIENTE_PK" PRIMARY KEY ("RUT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."PACIENTE" MODIFY ("SEXO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PACIENTE" MODIFY ("FECHA_NACI" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PACIENTE" MODIFY ("APELLIDO_MAT" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PACIENTE" MODIFY ("APELLIDO_PAT" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PACIENTE" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PACIENTE" MODIFY ("DV" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PACIENTE" MODIFY ("RUT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTIDA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."PARTIDA" ADD CONSTRAINT "PARTIDA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."PARTIDA" MODIFY ("PROVEEDOR_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PARTIDA" MODIFY ("FECHA_ENTREGA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PARTIDA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRESENTACION
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."PRESENTACION" ADD CONSTRAINT "PRESENTACION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."PRESENTACION" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PRESENTACION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" ADD CONSTRAINT "PROVEEDOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PROVEEDOR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECETA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."RECETA" ADD CONSTRAINT "RECETA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."RECETA" MODIFY ("PACIENTE_RUT" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RECETA" MODIFY ("USUARIO_NOM_USU" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RECETA" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RECETA" MODIFY ("HORA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RECETA" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RECETA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECETA_MEDICAMENTO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."RECETA_MEDICAMENTO" ADD CONSTRAINT "RELATION_7_PK" PRIMARY KEY ("MEDICAMENTO_CODIGO", "RECETA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."RECETA_MEDICAMENTO" MODIFY ("CANT_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RECETA_MEDICAMENTO" MODIFY ("UNIDAD_E" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RECETA_MEDICAMENTO" MODIFY ("EXTENSION" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RECETA_MEDICAMENTO" MODIFY ("UNIDAD_P" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RECETA_MEDICAMENTO" MODIFY ("PERIODICIDAD" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RECETA_MEDICAMENTO" MODIFY ("UNIDAD_C" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RECETA_MEDICAMENTO" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RECETA_MEDICAMENTO" MODIFY ("RECETA_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."RECETA_MEDICAMENTO" MODIFY ("MEDICAMENTO_CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGISTRO_MERMA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."REGISTRO_MERMA" MODIFY ("ID_REG" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."REGISTRO_MERMA" ADD CONSTRAINT "REGISTRO_MERMA_PK" PRIMARY KEY ("ID_REG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."REGISTRO_MERMA" MODIFY ("MEDICAMENTO_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."REGISTRO_MERMA" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."REGISTRO_MERMA" MODIFY ("HORA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."REGISTRO_MERMA" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."REGISTRO_MERMA" MODIFY ("MOTIVO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."REGISTRO_MERMA" MODIFY ("CANTIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_FUNC
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."TIPO_FUNC" ADD CONSTRAINT "TIPO_FUNC_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."TIPO_FUNC" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."TIPO_FUNC" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("NOM_USU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("FUNCIONARIO_RUT" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("CONTRASENA" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USUARIO" MODIFY ("NOM_USU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VIA_ADMINISTRACION
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."VIA_ADMINISTRACION" ADD CONSTRAINT "VIA_ADMINISTRACION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."VIA_ADMINISTRACION" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."VIA_ADMINISTRACION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FUNCIONARIO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."FUNCIONARIO" ADD CONSTRAINT "FUNCIONARIO_TIPO_FUNC_FK" FOREIGN KEY ("TIPO_FUNC_ID")
	  REFERENCES "PORTAFOLIO"."TIPO_FUNC" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEDICAMENTO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO" ADD CONSTRAINT "MEDICAMENTO_LABORATORIO_FK" FOREIGN KEY ("LABORATORIO_ID")
	  REFERENCES "PORTAFOLIO"."LABORATORIO" ("ID") ENABLE;
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO" ADD CONSTRAINT "MEDICAMENTO_NOM_GENERICO_FK" FOREIGN KEY ("NOM_GENERICO_ID")
	  REFERENCES "PORTAFOLIO"."NOM_GENERICO" ("ID") ENABLE;
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO" ADD CONSTRAINT "MEDICAMENTO_PRESENTACION_FK" FOREIGN KEY ("PRESENTACION_ID")
	  REFERENCES "PORTAFOLIO"."PRESENTACION" ("ID") ENABLE;
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO" ADD CONSTRAINT "MEDICAMENTO_VIA_ADMIN_FK" FOREIGN KEY ("VIA_ADMINISTRACION_ID")
	  REFERENCES "PORTAFOLIO"."VIA_ADMINISTRACION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEDICAMENTO_ACCION
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_ACCION" ADD CONSTRAINT "FK_ASS_10" FOREIGN KEY ("ACCION_FARM_ID")
	  REFERENCES "PORTAFOLIO"."ACCION_FARM" ("ID") ENABLE;
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_ACCION" ADD CONSTRAINT "FK_ASS_11" FOREIGN KEY ("MEDICAMENTO_CODIGO")
	  REFERENCES "PORTAFOLIO"."MEDICAMENTO" ("CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEDICAMENTO_COMPUESTO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_COMPUESTO" ADD CONSTRAINT "FK_ASS_8" FOREIGN KEY ("COMPUESTO_ID")
	  REFERENCES "PORTAFOLIO"."COMPUESTO" ("ID") ENABLE;
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_COMPUESTO" ADD CONSTRAINT "FK_ASS_9" FOREIGN KEY ("MEDICAMENTO_CODIGO")
	  REFERENCES "PORTAFOLIO"."MEDICAMENTO" ("CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEDICAMENTO_PARTIDA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_PARTIDA" ADD CONSTRAINT "FK_ASS_1" FOREIGN KEY ("PARTIDA_ID")
	  REFERENCES "PORTAFOLIO"."PARTIDA" ("ID") ENABLE;
  ALTER TABLE "PORTAFOLIO"."MEDICAMENTO_PARTIDA" ADD CONSTRAINT "FK_ASS_2" FOREIGN KEY ("MEDICAMENTO_CODIGO")
	  REFERENCES "PORTAFOLIO"."MEDICAMENTO" ("CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTIDA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."PARTIDA" ADD CONSTRAINT "PARTIDA_PROVEEDOR_FK" FOREIGN KEY ("PROVEEDOR_ID")
	  REFERENCES "PORTAFOLIO"."PROVEEDOR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECETA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."RECETA" ADD CONSTRAINT "RECETA_PACIENTE_FK" FOREIGN KEY ("PACIENTE_RUT")
	  REFERENCES "PORTAFOLIO"."PACIENTE" ("RUT") ENABLE;
  ALTER TABLE "PORTAFOLIO"."RECETA" ADD CONSTRAINT "RECETA_USUARIO_FK" FOREIGN KEY ("USUARIO_NOM_USU")
	  REFERENCES "PORTAFOLIO"."USUARIO" ("NOM_USU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECETA_MEDICAMENTO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."RECETA_MEDICAMENTO" ADD CONSTRAINT "FK_ASS_6" FOREIGN KEY ("MEDICAMENTO_CODIGO")
	  REFERENCES "PORTAFOLIO"."MEDICAMENTO" ("CODIGO") ENABLE;
  ALTER TABLE "PORTAFOLIO"."RECETA_MEDICAMENTO" ADD CONSTRAINT "FK_ASS_7" FOREIGN KEY ("RECETA_ID")
	  REFERENCES "PORTAFOLIO"."RECETA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGISTRO_MERMA
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."REGISTRO_MERMA" ADD CONSTRAINT "REGISTRO_MERMA_MEDICAMENTO_FK" FOREIGN KEY ("MEDICAMENTO_CODIGO")
	  REFERENCES "PORTAFOLIO"."MEDICAMENTO" ("CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."USUARIO" ADD CONSTRAINT "USUARIO_FUNCIONARIO_FK" FOREIGN KEY ("FUNCIONARIO_RUT")
	  REFERENCES "PORTAFOLIO"."FUNCIONARIO" ("RUT") ENABLE;
